FROM node:24-slim@sha256:242549cd46785b480c832479a730f4f2a20865d61ea2e404fdb2a5c3d3b73ecf

# Set the working directory to /build
WORKDIR /

# Copy the source code into the image for building
COPY internal/test/integration/components/nodejsdist .

# Install dependencies from committed lockfile
RUN npm ci

EXPOSE 5006

# Run the node app
CMD [ "node", "service-r.js" ]
